services:
  - type: web
    name: backend
    runtime: docker
    dockerfilePath: ./Dockerfile.backend
    plan: free
    envVars:
      - key: PORT
        value: 8081

  - type: web
    name: frontend
    runtime: node
    plan: free
    rootDir: ui
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: BACKEND_URL
        value: http://backend:8081
