services:
  - type: web
    name: backend
    env: java
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/p2p-1.0-SNAPSHOT.jar
    envVars:
      - key: PORT
        value: 8081

  - type: web
    name: frontend
    rootDir: ui
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
