version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8081:8081"
    expose:
      - "49152-65535"
    networks:
      - app-network
    dns:
      - 8.8.8.8
      - 1.1.1.1

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=https://p2pfile.up.railway.app
    depends_on:
      - backend
    networks:
      - app-network
    dns:
      - 8.8.8.8
      - 1.1.1.1

networks:
  app-network:
    driver: bridge
